import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DIVE2024",
  description: "Generated by KimCookieYa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className={"min-w-400 w-full h-screen mx-auto bg-bg-sea"}>
          {children}
        </div>
      </body>
    </html>
  );
}
